version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - LLM_ENDPOINT=http://host.docker.internal:11434/v1/completions
    volumes:
      - .:/app
      - shared_volume:/shared
    depends_on:
      - redis
      - db

  celery:
    build: .
    command: celery -A backend worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LLM_ENDPOINT=http://host.docker.internal:11434/v1/completions
    volumes:
      - .:/app
      - shared_volume:/shared
    depends_on:
      - redis
      - web

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  shared_volume: